api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from api.views import ArchiveViewSet, ArticleViewSet, ClientContactViewSet

router = SimpleRouter()

router.register('contact', ClientContactViewSet, basename='contact')
router.register('article', ArticleViewSet, basename='article')
router.register('archive', ArchiveViewSet, basename='archive')

urlpatterns = [
    path('journal/', include(router.urls)),
]

journal_template/urls.py
from django.urls import path

from .views import (
    AboutView,
    ArchiveDetailView,
    ArchiveView,
    ArticleDetailView,
    IndexView,
    InformationView,
)

app_name = 'journal_template'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('info_page/', InformationView.as_view(), name='info'),
    path('about/', AboutView.as_view(), name='about'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    path(
        'article_detail/<str:slug>/',
        ArticleDetailView.as_view(),
        name='article_detail',
    ),
    path(
        'archive_detail/<str:slug>/',
        ArchiveDetailView.as_view(),
        name='archive_detail',
    ),
]

open_journal_ru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = [
    path('', include('journal_template.urls', namespace='journals')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/about.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    {% for about in about_page %}
      <p class="fs-5">О журнале {{ about.journal }}</p>
      <p> {{ about.client_contact.email }} </p>
    {% endfor %}
{% endblock %}

templates/archive.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  {% cache 20 archive_page %}
    {% for article in archive_page %}
      <p class="fs-3">{{ article.issue_title }}</p>
      <p class="fs-3">{{ article.publish_date }}</p>
      <p>{{ article.article.article_title }}</p>
      <p>{{ article.article.author }}</p>
      <p>{{ article.article.category }}</p>
      <p class="fs-3">{{ article.article.id }}</p>
      {% thumbnail article.issue_img "200x300" crop="center" as im %}
        {% if article.issue_img %}
          <p><img src="{{ im.url }}" alt="journal's photo"></p>
        {% endif %}
      {% endthumbnail %}
      {% if article.all_issue_pdf %}
        <div class="">
          <a role="button"
             href="{{ article.all_issue_pdf.url }}"
             download="{{ article.all_issue_pdf.url }}"
             class="btn btn-light text-dark ml-0">
            Скачать весь номер
          </a>
        </div>
      {% endif %}
      <a role="button"
         href="{{ article.article.article_pdf.url }}"
         download="{{ article.article.article_pdf.url }}"
         class="btn btn-light text-dark ml-0">
        Скачать статью
      </a>
      <a href="{{ article.get_absolute_url }}">link</a>
    {% endfor %}
  {% endcache %}
  {% include 'includes/paginator.html' %}
{% endblock %}

templates/archive_detail.html
{% extends 'base.html' %}
{% load cache %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  {% cache 20 archive_detail %}
  <p>{{ archive_detail.issue_title }}</p>
  <p>{{ archive_detail.issue_number }}</p>
  {% if archive_detail.all_issue_pdf %}
    <div class="">
      <a role="button"
         href="{{ archive_detail.all_issue_pdf.url }}"
         download="{{ archive_detail.all_issue_pdf.url }}"
         class="btn btn-light text-dark ml-0">
        Скачать весь номер
      </a>
    </div>
  {% endif %}
  <a role="button"
     href="{{ archive_detail.article.article_pdf.url }}"
     download="{{ archive_detail.article.article_pdf.url }}"
     class="btn btn-light text-dark ml-0">
    Скачать статью
  </a>
  <a href="{{ archive_detail.article.get_absolute_url }}">link</a>
  {% endcache %}
{% endblock %}

templates/article_detail.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  <p class="mt-5">{{ article_page.author }}</p>
  <p class="mt-5">{{ article_page.article_title }}</p>
  <p class="mt-5">{{ article_page.keywords }}</p>
  <p class="mt-5">{{ article_page.summary }}</p>
  <p class="mt-5">{{ article_page.affiliation }}</p>
  {% if article_page.article_pdf %}
        <a role="button"
         href="{{ article_page.article_pdf.url }}"
         download="{{ article_page.article_pdf.url }}"
         class="btn btn-light text-dark ml-0">
        Скачать статью
      </a>
  {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{% block title %} Не забудьте прописать заголовок {% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  {% for cont in page_obj %}
    {% thumbnail cont.head_img "1800x200" crop="center" as im %}
    {% if cont.head_img %}
    <img src="{{ im.url }}" alt="some">
    {% endif %}
    {% endthumbnail %}
    <p class="mt-5 fs-1">{{ cont.title }}</p>
  {% endfor %}
  {{ last_number.issue_title }} <br>
  {{ last_number.issue_number }}
  {{ last_number.article.article_title }}
{% endblock %}

templates/info.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    {% for info in info_page %}
      <p class="fs-3">Информация для читателей {{ info.reader }}</p>
    {% endfor %}
    <form method="post" action="{% url 'journal_template:info' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
  </form>
{% endblock %}